### ISSUE TITLE
Problems with symlinks in 5.0.0

### ISSUE THREAD

**Issue by b00tsy** [vercel/pkg#1151]
Many thanks for putting in all the hard work recently to push pkg forward to support the latest node versions!

Unfortunately I think the behaviour has changed in the way pkg resolves files in symlinks, which currently results in a lot of `Cannot find module 'xy'` errors in one of my projects, which again results in a binary that actually misses the modules.

I have my project organized the following way with some shared helper code that is symlinked into each sub-project:

```
./ServiceA/package.json
./ServiceA/node_modules
./ServiceA/app.js
./ServiceA/Helper <- this is a symlink -> ../Helper
./ServiceB/package.json
./ServiceB/node_modules
./ServiceB/app.js
./ServiceB/Helper <- this is a symlink -> ../Helper
./Helper/someHelper.js
```

When pkg-ing eg. ServiceA pkg can't find all the modules `someHelper.js` is using. Everything worked well in pre-5.0.0 versions of pkg.

I could of course fix that by changing the build process of my project to copy eg. `ServiceA` to a tmp build dir and copy the Helper directory to that tmp build dir as well. But I wanted to ask first whether that change of how symlinks are handled is intended or whether that happened accidentally?

**Comment by erossignon** [comment]
Correct symlink support has been added to allow pnpm to be used.

I suspect that in your case
if /ServiceA/app.js  requires ./ServiceA/Helper it will end up loading ./Helper/someHelper.js and use ./ServiceA/node_modules  to fetch other modules 
if /ServiceB/app.js  requires ./ServiceB/Helper it will end up loading ./Helper/someHelper.js and use ./ServiceB/node_modules  to fetch other modules 
 
This is arguably ambiguous.

You will have to install the package used by ./Helper/someHelper.js either in ./Helper/node_modules or better in ./node_modules.
so that ./Helper/someHelper.js end up finding modules in a common place.

**Comment by b00tsy** [comment]
@erossignon Thanks for your response.

So you're saying this is something that changed from @4.x to @5.x or you assume it shouldn't work at all?

I build each service separately, the package.json / node_modules satisfies all requirements ./Helper/someHelper.js has. The folder ./Helper/ itself does not have a package.json / node_modules.

Eg: `(cd ./ServiceA; pkg -t node14-linux-x64 --out-path ./build .)`

For me everything worked fine with @4.x version.

**Comment by erossignon** [comment]
Can you create a repo with the most simplistic sample that reproduces the issue ?

**Comment by b00tsy** [comment]
Sure: https://github.com/b00tsy/PkgSymlinkExample

Works as described in README.md on macos with pkg@4.5.1, but not with pkg@5.0.0 (and also not running directly with node).

I just noticed the latter (not running with node) today. I usually run the code exactly that way in linux docker containers, where running with node@14 still works perfectly.

Maybe I just need to change my build process and use tmp directories, where I copy eg `ServiceA` and replace the symlink with a real copy of `Helper`...

**Comment by erossignon** [comment]
Thank for providing the repo, this safe a lof of investigation time

if you install the node_moudle folder and run any of your application in their respective folder you will get

```` 
0:~/pkg_issue1151/PkgSymlinkExample/Components/ServiceA$ node app.js 
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'asciiart-logo'
Require stack:
- /home/etienne/pkg_issue1151/PkgSymlinkExample/Components/Helper/someHelper.js
- /home/etienne/pkg_issue1151/PkgSymlinkExample/Components/ServiceA/app.js
````

This is the exact same behavior as with pkg@5.

The fact that pkg@4 produced something that 'worked' was a side effect. pkg@4 did not support symlink and was replacing them with a plain file instead.
The proof is that running "node app.js" does not work either.

The behavior of  pkg@5 is correct.

You may benefit from using a monorepo technique such as lerna, in your case.

**Comment by b00tsy** [comment]
Thank you for having a look into it.

When running `node app.js` within a linux docker container (which is my default dev environment) everything still works (see updated example repo). Folders `ServiceA` and `Helper` are bind mounted into the container (Helper still is a symlink). 

Still the way of doing things might be off standard and I understand that this is not how pkg handles things (as it handles it like node, which also doesn't work in my case) and I just was lucky that it worked on pkg@4.x. Meaning: I need to look into my build process / project structure.

Thanks for pointing my focus on `lerna`, I didn't know that, yet.

Issue solved!
